// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StrID with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StrID) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StrID with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StrIDMultiError, or nil if none found.
func (m *StrID) ValidateAll() error {
	return m.validate(true)
}

func (m *StrID) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 8 {
		err := StrIDValidationError{
			field:  "Id",
			reason: "value length must be at least 8 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StrIDMultiError(errors)
	}

	return nil
}

// StrIDMultiError is an error wrapping multiple validation errors returned by
// StrID.ValidateAll() if the designated constraints aren't met.
type StrIDMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StrIDMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StrIDMultiError) AllErrors() []error { return m }

// StrIDValidationError is the validation error returned by StrID.Validate if
// the designated constraints aren't met.
type StrIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StrIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StrIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StrIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StrIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StrIDValidationError) ErrorName() string { return "StrIDValidationError" }

// Error satisfies the builtin error interface
func (e StrIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStrID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StrIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StrIDValidationError{}

// Validate checks the field values on NumID with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NumID) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NumID with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NumIDMultiError, or nil if none found.
func (m *NumID) ValidateAll() error {
	return m.validate(true)
}

func (m *NumID) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := NumIDValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NumIDMultiError(errors)
	}

	return nil
}

// NumIDMultiError is an error wrapping multiple validation errors returned by
// NumID.ValidateAll() if the designated constraints aren't met.
type NumIDMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NumIDMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NumIDMultiError) AllErrors() []error { return m }

// NumIDValidationError is the validation error returned by NumID.Validate if
// the designated constraints aren't met.
type NumIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NumIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NumIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NumIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NumIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NumIDValidationError) ErrorName() string { return "NumIDValidationError" }

// Error satisfies the builtin error interface
func (e NumIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNumID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NumIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NumIDValidationError{}

// Validate checks the field values on StrIDs with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StrIDs) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StrIDs with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StrIDsMultiError, or nil if none found.
func (m *StrIDs) ValidateAll() error {
	return m.validate(true)
}

func (m *StrIDs) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := StrIDsValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StrIDsMultiError(errors)
	}

	return nil
}

// StrIDsMultiError is an error wrapping multiple validation errors returned by
// StrIDs.ValidateAll() if the designated constraints aren't met.
type StrIDsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StrIDsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StrIDsMultiError) AllErrors() []error { return m }

// StrIDsValidationError is the validation error returned by StrIDs.Validate if
// the designated constraints aren't met.
type StrIDsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StrIDsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StrIDsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StrIDsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StrIDsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StrIDsValidationError) ErrorName() string { return "StrIDsValidationError" }

// Error satisfies the builtin error interface
func (e StrIDsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStrIDs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StrIDsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StrIDsValidationError{}

// Validate checks the field values on NumIDs with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NumIDs) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NumIDs with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NumIDsMultiError, or nil if none found.
func (m *NumIDs) ValidateAll() error {
	return m.validate(true)
}

func (m *NumIDs) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := NumIDsValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NumIDsMultiError(errors)
	}

	return nil
}

// NumIDsMultiError is an error wrapping multiple validation errors returned by
// NumIDs.ValidateAll() if the designated constraints aren't met.
type NumIDsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NumIDsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NumIDsMultiError) AllErrors() []error { return m }

// NumIDsValidationError is the validation error returned by NumIDs.Validate if
// the designated constraints aren't met.
type NumIDsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NumIDsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NumIDsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NumIDsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NumIDsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NumIDsValidationError) ErrorName() string { return "NumIDsValidationError" }

// Error satisfies the builtin error interface
func (e NumIDsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNumIDs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NumIDsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NumIDsValidationError{}

// Validate checks the field values on Num with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Num) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Num with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NumMultiError, or nil if none found.
func (m *Num) ValidateAll() error {
	return m.validate(true)
}

func (m *Num) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return NumMultiError(errors)
	}

	return nil
}

// NumMultiError is an error wrapping multiple validation errors returned by
// Num.ValidateAll() if the designated constraints aren't met.
type NumMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NumMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NumMultiError) AllErrors() []error { return m }

// NumValidationError is the validation error returned by Num.Validate if the
// designated constraints aren't met.
type NumValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NumValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NumValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NumValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NumValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NumValidationError) ErrorName() string { return "NumValidationError" }

// Error satisfies the builtin error interface
func (e NumValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNum.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NumValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NumValidationError{}

// Validate checks the field values on Bool with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Bool) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Bool with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BoolMultiError, or nil if none found.
func (m *Bool) ValidateAll() error {
	return m.validate(true)
}

func (m *Bool) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return BoolMultiError(errors)
	}

	return nil
}

// BoolMultiError is an error wrapping multiple validation errors returned by
// Bool.ValidateAll() if the designated constraints aren't met.
type BoolMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoolMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoolMultiError) AllErrors() []error { return m }

// BoolValidationError is the validation error returned by Bool.Validate if the
// designated constraints aren't met.
type BoolValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoolValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoolValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoolValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoolValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoolValidationError) ErrorName() string { return "BoolValidationError" }

// Error satisfies the builtin error interface
func (e BoolValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBool.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoolValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoolValidationError{}

// Validate checks the field values on Str with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Str) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Str with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StrMultiError, or nil if none found.
func (m *Str) ValidateAll() error {
	return m.validate(true)
}

func (m *Str) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return StrMultiError(errors)
	}

	return nil
}

// StrMultiError is an error wrapping multiple validation errors returned by
// Str.ValidateAll() if the designated constraints aren't met.
type StrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StrMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StrMultiError) AllErrors() []error { return m }

// StrValidationError is the validation error returned by Str.Validate if the
// designated constraints aren't met.
type StrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StrValidationError) ErrorName() string { return "StrValidationError" }

// Error satisfies the builtin error interface
func (e StrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StrValidationError{}

// Validate checks the field values on StrMap with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StrMap) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StrMap with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StrMapMultiError, or nil if none found.
func (m *StrMap) ValidateAll() error {
	return m.validate(true)
}

func (m *StrMap) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return StrMapMultiError(errors)
	}

	return nil
}

// StrMapMultiError is an error wrapping multiple validation errors returned by
// StrMap.ValidateAll() if the designated constraints aren't met.
type StrMapMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StrMapMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StrMapMultiError) AllErrors() []error { return m }

// StrMapValidationError is the validation error returned by StrMap.Validate if
// the designated constraints aren't met.
type StrMapValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StrMapValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StrMapValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StrMapValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StrMapValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StrMapValidationError) ErrorName() string { return "StrMapValidationError" }

// Error satisfies the builtin error interface
func (e StrMapValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStrMap.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StrMapValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StrMapValidationError{}

// Validate checks the field values on Sort with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Sort) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sort with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SortMultiError, or nil if none found.
func (m *Sort) ValidateAll() error {
	return m.validate(true)
}

func (m *Sort) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Field

	// no validation rules for Order

	if len(errors) > 0 {
		return SortMultiError(errors)
	}

	return nil
}

// SortMultiError is an error wrapping multiple validation errors returned by
// Sort.ValidateAll() if the designated constraints aren't met.
type SortMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SortMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SortMultiError) AllErrors() []error { return m }

// SortValidationError is the validation error returned by Sort.Validate if the
// designated constraints aren't met.
type SortValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SortValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SortValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SortValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SortValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SortValidationError) ErrorName() string { return "SortValidationError" }

// Error satisfies the builtin error interface
func (e SortValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSort.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SortValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SortValidationError{}
